---
- name: Webserver provisioning
  hosts: web

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Deploy simple html page
      template:
        src: "{{ src_web_page }}"
        dest: "{{ dst_web_page }}"
